name: goreleaser

on:
  push:
    tags:
      - v*.*.*

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version-file: go.mod
      - uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7
        with:
          # You can pass flags to goreleaser via GORELEASER_ARGS
          # --clean will save you deleting the dist dir
          args: release --clean
          distribution: goreleaser # or 'goreleaser-pro'
          version: "~> v2" # or 'latest', 'nightly', semver
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
